parameters: {
  H_sh_300_options: {
    3d-attention: {
      dim: 16,
      depth: 6,
      dropout: 0.001
    }
  },
  etf_50_options: {
    3d-attention: {
      dim: 16,
      depth: 6,
      dropout: 0.001
    }
  }
}