parameters: {
  h_sh_300_option: {
    3d-attention: {
      dim: 16,
      depth: 5,
      dropout: 0.01
    }
  },
  ETF50-option: {
    3d-attention: {
      dim: 38,
      depth: 8,
      dropout: 0.0001
    }
  }
}