parameters: {
  H_sh_300_options: {
    3d-attention: {
      dim: 32,
      depth: 4,
      dropout: 0.01
    }
  },
  etf_50_options: {
    3d-attention: {
      dim: 32,
      depth: 4,
      dropout: 0.01
    }
  }
}