# General parameters

dataset: ETF50-option
prepare_home_path: '/home/liyu/data/hedging-option/20170101-20230101/'

#dataset: h_sh_300_option
#prepare_home_path: '/home/liyu/data/hedging-option/20170101-20230101/index-option/'

objective: regression  # Don't change binary_f1 binary
# 如果是 binary或者 regression 那么num_classes为1

learning_rate: 0.0001


normal_type: 'mean_norm'
use_much_features: False


# optimize_hyperparameters: True
use_gpu: True
# use one GPU parameters
gpu_index: 5
# use GPU data_parallel parameters
gpu_ids: [ 0, 1, 2, 3, 4, 5, 6, 7]


data_parallel: False


# Preprocessing parameters
scale: False
target_encode: False
one_hot_encode: False

# Training parameters
batch_size: 1
val_batch_size: 1
early_stopping_rounds: 20
epochs: 500
logging_period: 20



# About the data
num_classes: 1  # for classification
#num_features: 180
#cat_idx: [ 35, 71, 107, 143, 179]
#cat_dims: [ 2, 2, 2, 2, 2 ]

num_features: 30
cat_idx: [ ]
# cat_dims: will be automatically set.
#cat_dims: [ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ]